### ISSUE TITLE
SerializationUtility.Serialize is not a valid function

### ISSUE THREAD

**Issue by SwitchNZ** [TeamSirenix/odin-serializer#1]
Hi devs,

In your development readme you quote an example using "SerializationUtility.Serialize(data)" 

This function does not exist in the released package. You can call the individual functions to serialize but this omission/error is very confusing if you are just trying to just "plug and play" and follow your examples.

**Comment by willnode** [comment]
I'm just playing with this and was confused. 

But I found `SerializationUtility.SerializeValue(data, DataFormat.Binary)`. Maybe this one is correct?

**Comment by TorVestergaard** [comment]
You're indeed correct, the code examples should have used the SerializeValue/DeserializeValue methods - a simple typing error and forgetting to check if the code actually compiled - my mistake! It's been corrected now.
