### ISSUE TITLE
linux errors when open project (install/setup)

### ISSUE THREAD

**Issue by rakkarage** [TeamSirenix/odin-serializer#11]
tried code and get warnings about 3 versions of same function? deleted 2 to test and get other error idk? should this work from Linux too idk thanks

what is the process? i am supposed to load that sceneButtons and build a debug dll and generate a unity package and copy that to my project?

sorry idk thanks

> PrecompiledAssemblyException: Multiple precompiled assemblies with the same name OdinSerializer.dll included for the current platform. Only one assembly with the same name is allowed per platform. Assembly path: {0}
UnityEditor.Scripting.ScriptCompilation.EditorBuildRules.CreateTargetAssemblies (System.Collections.Generic.IEnumerable`1[T] customScriptAssemblies, System.Collections.Generic.IEnumerable`1[T] precompiledAssemblies) (at /home/builduser/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorBuildRules.cs:251)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.UpdateCustomTargetAssemblies () (at /home/builduser/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:701)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.SetAllCustomScriptAssemblyJsonContents (System.String[] paths, System.String[] contents, System.String[] guids) (at /home/builduser/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:1011)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface.SetAllCustomScriptAssemblyJsonContents (System.String[] allAssemblyJsonPaths, System.String[] allAssemblyJsonContents, System.String[] guids) (at /home/builduser/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:241)

i have the store bought one too and that seems to work without errors but i only wanted the serialize to be distributable

**Comment by TorVestergaard** [comment]
I believe recent changes should have fixed this, but if you can confirm that this is not the case, please comment here to reopen the issue.
