### ISSUE TITLE
Issue when serializing abstract classes as private members.

### ISSUE THREAD

**Issue by jamilan** [TeamSirenix/odin-serializer#12]
Hi!

I was trying to use Odin Inspector and found that one of our classes was not serializing at all the it was rendered by Odin, but it was working properly when excluded.

After some debugging, I found that Odin was crashing on MemberInfoExtensions.GetAttributes due to a private member which is an abstract class, an actual native c# class. No dependencies with Unity.

I manage to fix the issue by swapping Odin to Sources and modifying the source code as provided in the path file. (renamed to txt as requested by GitHub)

[MemberInfoExtensions-patch.diff.txt](https://github.com/TeamSirenix/odin-serializer/files/2975680/MemberInfoExtensions-patch.diff.txt)

If would be great If you do not find any incompatibilities with it and could integrate the fix in the binary version.

Thanks for your time!
Jose

**Comment by TorVestergaard** [comment]
I've committed a fix that should take care of this.

**Comment by jamilan** [comment]
Thanks!
