### ISSUE TITLE
Misplaced EndSample in static SirenixAssetPaths()

### ISSUE THREAD

**Issue by kimhutchison** [TeamSirenix/odin-serializer#15]
The BeginSample is inside the editor ifdef, where as the EndSample is outside.

**Comment by TorVestergaard** [comment]
SirenixAssetPaths is an Odin Inspector class which does not exist in the serializer, so this issue doesn't really belong here, but the reported issue has now been fixed in Odin Inspector's patch 2.0.17, so I will close it here.
