### ISSUE TITLE
Cannot Open "Build" folder in Unity 2019.1

### ISSUE THREAD

**Issue by KyleStank** [TeamSirenix/odin-serializer#17]
Hello.

First off, I am assuming that I am having this problem because Unity 2019.1 was JUST released. However, I figured I would open an issue just so you guys can see.

When I download odin-serializer and open the project, I cannot open it **properly** in Unity 2019.1. This does work in Unity 2018.3, however.

**Here is what I mean.**

1. Open Unity Hub
2. Click **Open**
3. Navigate to the odin-serializer folder and double-click the **Build** folder
4. Wait for Unity to load
5. Once Unity is loaded, **no scene view buttons are present**.

This is an issue since the README.md says that the recommended way to build the project is through Unity.

Any ideas on how I could fix this?

Thanks,
Kyle

**Comment by mcguinnessdr** [comment]
Here's a build that works with 2019.1 https://www.dropbox.com/s/yrhg2bhbnirj8i3/Odin%20Serializer.unitypackage?dl=0

**Comment by KonstantinPlaytino** [comment]
Hello,
I just encountered the same issue and I used the unofficial build mentioned above. First it worked but now I am trying to test AOT and I get an error message. Is this releated some how? I also using Unity 2019.1
![image](https://user-images.githubusercontent.com/50205280/57603673-947d5f80-7562-11e9-91f2-3a83cec69396.png)

**Comment by TorVestergaard** [comment]
If you build from the latest master commit, this *should* be fixed, along with a lot of other fixes and improvements. We just haven't had the time to do a new release for a bit, though one will be coming soon along with the new Odin Inspector 2.1 patch.

**Comment by Moravec-Jan** [comment]
I made the build and it indeed solves the issue. You can download unitypackage [here](https://mega.nz/#!8B0XXKrY!Co7MsmqGjF_dIkQZt_aCr37fXL1LpN2Y8VC3EOjSnts).

**Comment by TorVestergaard** [comment]
I believe this issue has been resolved by now? Please comment to reopen if this isn't the case.
