### ISSUE TITLE
Nodes data formatting not compatible with Addressables/SBP builds

### ISSUE THREAD

**Issue by Jobus0** [TeamSirenix/odin-serializer#19]
While using `Editor Serialization Format: Nodes`, Odin-serialized data is lost on building the Player Content data in Addressables. But when switching to Binary or JSON for editor, it works as expected.

It seems like the serializer simply doesn't detect [SBP](https://docs.unity3d.com/Packages/com.unity.scriptablebuildpipeline@1.4/manual/index.html) builds to know to use the build serialization format instead.

From a quick and naive test, it seems like checking for `typeof(UnityEditor.Build.Pipeline.ContentPipeline)` (along with the old build pipeline) at **UnitySerializationUtility:424** does the trick. But I only tested it with Addressable's 'Build Player Content' option with a BundledAssetGroupSchema.

**Comment by TorVestergaard** [comment]
Thanks for the report, will have to give this a look.

**Comment by TorVestergaard** [comment]
This issue should hopefully be fixed by [this commit](https://github.com/TeamSirenix/odin-serializer/commit/1f9166cceef49101f45a846f295ba1412ab3a6ca).
