### ISSUE TITLE
Does SerializationPolicies.Unity Serializes Auto-Properties?

### ISSUE THREAD

**Issue by willnode** [TeamSirenix/odin-serializer#2]
https://github.com/TeamSirenix/odin-serializer/blob/ecd5ee6cf3d71b654b62926f85e699a3db47d9f6/OdinSerializer/Core/Misc/SerializationPolicies.cs#L108-L112

However, 

```c#
public class Sample : MonoBehaviour
{
	public class Foo
	{
		public int Bar { get; set; }
	}
	void Start()
	{
		Debug.Log(Encoding.UTF8.GetString(SerializationUtility.SerializeValue(new Foo(), DataFormat.JSON)));
	}
}
```
returns:
```json
{
	"$id": 0,
	"$type": "0|Sample+Foo, Assembly-CSharp"
}
```

So then i'm not sure which one is correct.

**Comment by TorVestergaard** [comment]
As the documentation you quote states, the auto-property must be marked with [OdinSerialize] in order for the policy to serialize it.

**Comment by willnode** [comment]
Oops, you're right, I think I misunderstood the wording. Sorry!

> Public fields *and* (fields or auto-properties marked with ..) <-- Wasn't aware to read this.

**Comment by TorVestergaard** [comment]
That's perfectly understandable, really - we should probably add a comma in there to make the separation between the two cases clearer :)

**Comment by TorVestergaard** [comment]
I can add that I have now clarified the documentation for the Unity and Strict policies, so it should be better now.

**Comment by willnode** [comment]
I see, the doc is much better now. Thanks!
