### ISSUE TITLE
Serialization of built-in Unity ScriptableObject: TimelineAsset

### ISSUE THREAD

**Issue by 4quet** [TeamSirenix/odin-serializer#21]
Hello,
I'm trying to serialize a [TimelineAsset](https://docs.unity3d.com/2017.3/Documentation/ScriptReference/Timeline.TimelineAsset.html), which is a built-in ScriptableObject that stores Timeline related data. The TimelineAsset stores multiple references to other ScriptableObjects such as [TrackAssets](https://docs.unity3d.com/2017.3/Documentation/ScriptReference/Timeline.TrackAsset.html) and [TimelineClips](https://docs.unity3d.com/2017.3/Documentation/ScriptReference/Timeline.TimelineClip.html).
Is there a way to serialize a TimelineAsset and all its children assets using Odin serializer ?

- I can't make TimelineAsset to inherit from `SerializedScriptableObject` since it's a built-in class.
- I have noticed TimelineAsset already inherits from the `ISerializationCallbackReceiver` interface.

I already tried to serialize it by using:
```C#
byte[] lData = SerializationUtility.SerializeValue<TimelineAsset>(mTimeline, DataFormat.JSON);
```
but this gives me several warnings like this one:
```
A formatter has been created for the UnityEngine.Object type TimelineAsset - this is *strongly* discouraged.
Unity should be allowed to handle serialization and deserialization of its own weird objects.
Remember to serialize with a UnityReferenceResolver as the external index reference resolver in the serialization context.
```
I must admit I don't really understand what the `SerializationContext` and `DeserializationContext` are used for.

If I try to deserialize the previously serialized data using:
```C#
byte[] lData = File.ReadAllBytes(lPath);
mTimeline = SerializationUtility.DeserializeValue<TimelineAsset>(lData, DataFormat.JSON);
```
Then the object returned by `DeserializeValue()` is null.

Any help is much appreciated !

**Comment by TorVestergaard** [comment]
Please read the readme sections about basic usage of OdinSerializer, and about how it works in Unity, as those sections explain all this.

**Comment by JeReT** [comment]
came here through google. The answer is very dissatisfying @TorVestergaard

**Comment by z3nth10n** [comment]
https://odininspector.com/tutorials/serialize-anything/serializing-without-serialized-base-classes here explains why, you should serialize the List which is output from `SerializationUtility.SerializeValue(originalData, dataFormat, out unityObjectReferences)`
