### ISSUE TITLE
[Questions] Serialization in edit mode

### ISSUE THREAD

**Issue by MCrafterzz** [TeamSirenix/odin-serializer#22]
Writing editor tools it's always so irritating to find out that a object resets on reload(open project/code recompile etc) jut because it's a dictionary or a list with custom classes for example. So I wander If this tool can be used to solve that problem, serialising non-compatable types in edit mode or does it only work for saving data in play mode? Also if it's possible can you nudge me in the right direction? Thanks.

**Comment by TorVestergaard** [comment]
As noted in the readme, OdinSerializer indeed lets you persist data across reloads and store the data in normal Unity assets and game objects, but you have to write the editors for it all by yourself, and handle marking objects dirty, and Undo, and everything else. And god help you if you try to make prefabs work! :)

If you want something that handles all of that for you, you should have a look at [Odin Inspector](odininspector.com).
