### ISSUE TITLE
[2019.1] Error on installing

### ISSUE THREAD

**Issue by MCrafterzz** [TeamSirenix/odin-serializer#23]
Hey, when I install the latest version from downloads it gives errors in 2019.1.0f2:
Assembly 'Assets/Plugins/Sirenix/Odin Serializer/EditorOnly/OdinSerializer.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEngine.Networking'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

I have looked in the package manager and can't find anything related to networking so have I missed something?

**Comment by yanjingzhaisun** [comment]
Hi MCrafterzz,

We've met the same problem. How do you solve it?

Best,
YJZ

**Comment by TorVestergaard** [comment]
You merely need to build from the latest source, where the issue is fixed. A new, updated release of the serializer will be coming when the 2.1 patch of Odin Inspector is released.

**Comment by yanjingzhaisun** [comment]
Thanks!
