### ISSUE TITLE
AOT generate didn't generate any support serialized type on ScriptableObject.

### ISSUE THREAD

**Issue by poppuchan** [TeamSirenix/odin-serializer#3]
public class DBImages : SerializedScriptableObject
    {
     
        [OdinSerialize]
        Dictionary<Enum.ItemIdentity, string> _dbItem = new Dictionary<Enum.ItemIdentity, string>();

        [OdinSerialize]
        Dictionary<Enum.MonsterElement, string> _dbMonsterElement = new Dictionary<Enum.MonsterElement, string>();

        [OdinSerialize]
        Dictionary<PGGame.Enum.SkillIdentity, string> _dbSkill = new Dictionary<PGGame.Enum.SkillIdentity, string>();

		[OdinSerialize]
		Dictionary<Tactics.TacticCtrl.TacticsMode, string> _dbTactic = new Dictionary<Tactics.TacticCtrl.TacticsMode, string>();
        
        public static Sprite Get(Enum.ItemIdentity e)
        {
            
            
            try
            {
                DBImages db = DBImages.Instance;
                if (db == null)
                    return null;

                if (!db._dbItem.ContainsKey(e))
                    return null;
         
                try
                {
                    return Resources.Load<Sprite>(db._dbItem[e]);
                }
                catch 
                {
                    Debug.LogError("DBImages unable to load sprite at:" + db._dbItem[e]);
                    return null; 
                }
            }
            catch(Exception er) {
                Debug.LogError(er.Message);
                return null; 
            }
            
        }

        public static Sprite Get(Enum.MonsterElement e)
        {
            if (!Instance._dbMonsterElement.ContainsKey(e))
                return null;

            return Resources.Load<Sprite>(Instance._dbMonsterElement[e]);
        }
        
        public static Sprite Get(PGGame.Enum.SkillIdentity e)
        {
            if (!Instance._dbSkill.ContainsKey(e))
                return null;

            return Resources.Load<Sprite>(Instance._dbSkill[e]);
        }

		public static Sprite Get(Tactics.TacticCtrl.TacticsMode e)
		{
			if (!Instance._dbTactic.ContainsKey(e))
				return null;
			return Resources.Load<Sprite>(Instance._dbTactic[e]);
        }

        

        #region Base Part
        public static readonly string kFileName = "DB.Images.asset";
        public static readonly string kFolder = "Assets/GeneratedScripts/Resources/";
        public static readonly string kFullPath = kFolder + kFileName;

        private static DB.DBImages _instance;

        public static DB.DBImages Instance
        {
            get{
                
                if (_instance == null)
                {
                    try
                    {
                        _instance = Resources.Load<DB.DBImages>(kFileName.RemoveFilenameExtension());
                    }
                    catch
                    {
                        throw new Exception("Unable to load DB.Image"); 
                    }
                }
                if (_instance == null)
                {
                    Debug.LogWarning("DB.DBImages not found. Make sure it is created");
                }

                return _instance;
            }
        }

This is my code.
I tried many way and search many site to solve this but nothing work for me.
In AOT Generate's message box told It'll scan the entire project.
In reality , it just scan and get serialized type in **Every Scene** , not entire project.
It didn't get serialized type on ScriptableObject.(yes! It isn't Monobehavior , It can't be in any scene)
And it just leave me a empty support serialized types list.

**Comment by TorVestergaard** [comment]
What AOT generate message box are you talking about? Are you using Odin Inspector, or just Odin Serializer?

**Comment by poppuchan** [comment]
I use Odin Inspector.

**Comment by poppuchan** [comment]
and this is AOT generate message box.
![image](https://user-images.githubusercontent.com/19602963/42373534-6266fce4-813f-11e8-9175-607a9408d057.png)

**Comment by TorVestergaard** [comment]
This is the repository for Odin Serializer, not Odin Inspector. Please report this issue on the [Odin Inspector issue tracker](https://bitbucket.org/sirenix/odin-inspector/issues), and make sure to answer all of the questions listed in your issue text, when you submit the issue.

**Comment by poppuchan** [comment]
I apologize for submit in the wrong place and thank you for your help :)
