### ISSUE TITLE
AOT dll before building

### ISSUE THREAD

**Issue by loic-lopez** [TeamSirenix/odin-serializer#35]
Hi,

Does is it possible to use `Odin's AOT generation feature to generate an AOT dll before building` without odin inspector?

I'm trying to use odin-serializer in an UWP application.

Thanks for reply

**Comment by TorVestergaard** [comment]
Yes, the front page readme contains details on this, [here](https://github.com/TeamSirenix/odin-serializer#aot-support-details).
