### ISSUE TITLE
Changing Polymorphic class list order and hiding members

### ISSUE THREAD

**Issue by HyperGamesDev** [TeamSirenix/odin-serializer#50]
Hello
The asset is great, im just starting to get some value out of it!
But one thing thats bothering me right now is Polymorphic class lists, they cant be reordered..
![image](https://user-images.githubusercontent.com/48921794/143589449-8870a8a7-7fda-4949-8c90-dc88b9ca26a4.png)
Also I want to hide the one starting with "_" from the list
(I have the value above from before I knew Odin could be setting them from a list like that, its a enum that just Validates)

**Comment by TorVestergaard** [comment]
I'm afraid Odin Serializer has nothing to do with drawing of data in the inspector. This looks like an Odin Inspector issue, which should be reported [here](https://bitbucket.org/sirenix/odin-inspector/issues). I can say that this looks like it will be resolved by the new type/value selection feature which we plan to implement in Odin Inspector 3.1.

Regardsless, I'm closing this issue as it is not related to Odin Serializer.
