### ISSUE TITLE
Alternative untyped deserializer?

### ISSUE THREAD

**Issue by myocytebd** [TeamSirenix/odin-serializer#54]
Is it possible to make an untyped deserializer?  
(Deserialize to some weakly typed tree, or just fire callbacks like emitString(), emitObjectBegin() etc.)
It seems that odin-serializer's binary format stores sufficient data to restore a JSON-like tree with type name.  
However the deserialzer is strongly dependent on runtime type and cannot be used if type is unavailable.  

What I want is to export game's serialized data for modding, in offline tools.  
(Export to untyped format like Json.NET, so that it is easy to format/reuse in other types)  

The binary format seems clear, and BinaryDataReader can be reused.  
But the the state machine of deserializer + formatter seems to be tricky, I am unclear how to replicate it.

**Comment by TorVestergaard** [comment]
Hmm, this is a good question. What you're talking about is definitely possible, but nothing like it exists at the moment; you would need to write your own utility that uses an IDataReader to read out the format and convert it to anything you want, possibly by using an IDataWriter to convert it into json or something like it. At least, that is what I would suggest. Formatters require types, as they are what convert types to and from the sets of data primitives that the data writers/reader interfaces support.
